on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  release:
    types: [edited, published]

jobs:
  my_job:
    if : always()
    runs-on: ubuntu-22.04

    steps:
      - name: testing echo command
        run: echo testfile
        if: "${{ github.actor == 'suniljamadar'}}"
