on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  release:
    types: [edited,published]

jobs:
  build:
    name: test
    runs_on: ubuntu-latest
    
    steps:
      - name: testing echo command
        run: echo testfile
