on:
  push:
    branches:
      - main
  #   tags:
  #     - '[0-9]+.[0-9]+.[0-9]+'
  # release:
  #   types: [edited, published]

env:
  CHANNEL: "IAC_NOTIFICATION_CHANNEL"
  PWD: ${{ secrets.TFE_URL }}

jobs:
  my_job:
    if : always()
    runs-on: ubuntu-22.04

    steps:
      - name: print env secret value
        run: echo ${{ env.PWD }}"
        
      - name: testing echo command
        if: ${{ env.PWD }} != 'suniljamadar'
        run: echo testfile
      
      - name: command
        if: ${{ github.event.commits[0].author.name == 'suniljamadar' }}
        run: echo filing tax
      
      - name: print env value
        run: echo ${{ env.CHANNEL}}

      - name: print secret value
        run: echo ${{ secrets.TFE_URL }}${{ github.event.commits[0].author.name }}
